### ISSUE TITLE
Just installed the plugin and got chinese lang

### ISSUE THREAD

**Issue by vitalijalbu** [apptools-lab/AppWorks#1011]
Just installed the plugin and got chinese lang, but my default lang is italian
Plugin name: Time Master

**Comment by fyangstudio** [comment]
It support chinese lang and en lang.  you can change it to en lang

**Comment by vitalijalbu** [comment]
where to change it?

**Comment by KoljaL** [comment]
The editor language has to be English, otherwise the Plugin is in Chinese:

https://code.visualstudio.com/docs/getstarted/locales
