### ISSUE TITLE
Cursor placement

### ISSUE THREAD

**Issue by hisbvdis** [apptools-lab/AppWorks#1019]
### Problem Description
When autocomplete typing, cursor places after closing braces.
IMHO, it is not comfortable, because i need to type between braces.
Maybe it makes sense to put the cursor between the brackets.

### Proposed proposal/Proposal
Just as it is done in the VS Code:
1. Place cursor before opening braces, allowing to type braces and type beetween them
2. Or place cursor inside braces block

![bandicam 2022-05-31 11-38-16-669](https://user-images.githubusercontent.com/5147554/171132628-25f0c329-e9ef-4b68-89eb-c5ef606792aa.gif)

**Comment by fyangstudio** [comment]
This issue will be fixed in our next release.

**Comment by fyangstudio** [comment]
React Style Helper v1.1.2
