### ISSUE TITLE
React Style Helper 插件不支持中括号

### ISSUE THREAD

**Issue by izilongwan** [apptools-lab/AppWorks#1020]
插件名/Extension: React Style Helper 

## 您的本地环境信息/Your local environment information

* 操作系统及其版本/System and Version: any
* Node version: any
* npm version: any

## 您遇到的问题及复现步骤/What are your problems and how to reproduce them
styles.name_get-do 带有中横行的类名应该改写成styles['name_get-do']

## 您期待的正确结果/The right result you're looking forward to
styles['name_get-do']

**Comment by fyangstudio** [comment]
感谢反馈， 确实应该优化下。 下个版本修复此问题

**Comment by fyangstudio** [comment]
React Style Helper v1.1.2
