### ISSUE TITLE
使用npm publish 发布区块时报错，但是生成了screenshot.png，走appworks generate时说这个区块未发布，请问有啥解决方法吗

### ISSUE THREAD

**Issue by shizhibiao** [apptools-lab/AppWorks#1027]
![image](https://user-images.githubusercontent.com/37282986/174702043-895202af-4daa-43be-9f4b-cb9e51c1d49f.png)

**Comment by luhc228** [comment]
https://appworks.site/materials/get_start.html#%E5%8D%95%E4%B8%AA%E7%89%A9%E6%96%99%E5%BC%80%E5%8F%91

需要先执行 npm publish 发布到 npm 上

**Comment by shizhibiao** [comment]
现在就是使用npm publish发布然后报错了，但是生成了screenshot.png图片

**Comment by shizhibiao** [comment]
> https://appworks.site/materials/get_start.html#%E5%8D%95%E4%B8%AA%E7%89%A9%E6%96%99%E5%BC%80%E5%8F%91
> 
> 需要先执行 npm publish 发布到 npm 上

在就是使用npm publish发布然后报错了，但是生成了screenshot.png图片

**Comment by shizhibiao** [comment]
> https://appworks.site/materials/get_start.html#%E5%8D%95%E4%B8%AA%E7%89%A9%E6%96%99%E5%BC%80%E5%8F%91
> 
> 需要先执行 npm publish 发布到 npm 上

这个问题也在刚发给您的代码片段里面（需求#1028），可以帮忙一起看看吗谢谢
