### ISSUE TITLE
插件打不开， 打开就闪退， 这个是真的可以用吗

### ISSUE THREAD

**Issue by zhengguo07q** [apptools-lab/AppWorks#1045]
插件名/Extension: 

## 您的本地环境信息/Your local environment information

* 操作系统及其版本/System and Version: 
* Node version: 
* npm version:

**Comment by sun96013** [comment]
同上也碰到这个问题，一开始以为是版本和环境的问题。后来全部装完了还是一样

**Comment by luhc228** [comment]
已修复
