### ISSUE TITLE
在vsCode中点击appworks选择模板创建应用时黑屏

### ISSUE THREAD

**Issue by JUNHAN12138** [apptools-lab/AppWorks#1062]
插件名/Extension: 

## 您的本地环境信息/Your local environment information

* 操作系统及其版本/System and Version: 
* Node version: 
* npm version: 

## 您遇到的问题及复现步骤/What are your problems and how to reproduce them

![image](https://user-images.githubusercontent.com/65531323/225536417-c6b1d745-90bd-4903-be0a-f1a9241de9c4.png)
啥也没有

**Comment by luhc228** [comment]
恢复了
