### ISSUE TITLE
这个项目是闭源了吗，还是已经放弃了，现在什么情况，升级版本后直接要阿里内部地址登录，请官方给个解释

### ISSUE THREAD

**Issue by pjki100** [apptools-lab/AppWorks#1075]
![image](https://github.com/apptools-lab/AppWorks/assets/6637531/7eabdde3-937e-43e9-aa6d-d78ccc60c30a)

**Comment by luhc228** [comment]
@pjki100  原来 [AppWorks](https://marketplace.visualstudio.com/items?itemName=iceworks-team.iceworks) 老版本的可以用，新版本的 [AppWorks](https://marketplace.visualstudio.com/items?itemName=iceworks-team.appworks) 目前是只给内部使用

**Comment by pjki100** [comment]
老版本是哪一个，请发个地址出来

**Comment by luhc228** [comment]
> 老版本是哪一个，请发个地址出来

https://marketplace.visualstudio.com/items?itemName=iceworks-team.iceworks
