### ISSUE TITLE
RFC: 基于场景图片智能生成代码

### ISSUE THREAD

**Issue by alvinhui** [apptools-lab/AppWorks#463]
## 问题是什么？

一些前端场景，例如表单、表格、列表，其设计模式比较固定，基于图片生成代码的可行性较高。
可以识别图片中的控件，得出图片中的元素组成信息，根据信息匹配转换成前端代码，由此节约设计师资源，提升前端开发效率。

## 怎么做？

1. 选择识别类型（表单、表格）
    ![image](https://user-images.githubusercontent.com/4392234/91379412-378be280-e855-11ea-94bf-ba2f062504a0.png)
2. 上传图片
    ![image](https://user-images.githubusercontent.com/4392234/91379457-538f8400-e855-11ea-86c3-771133a335f6.png)
3. 识别图片
    ![image](https://user-images.githubusercontent.com/4392234/91379751-f5af6c00-e855-11ea-954f-c70d00d28e87.png)
4. 生成代码
5. 效果评估
    ![image](https://user-images.githubusercontent.com/4392234/91381372-d1558e80-e859-11ea-9c6a-e8fad7669c09.png)

### 参考

- imgcook: https://www.imgcook.com/
- AI 组件识别：http://suo.im/5TENcj

## 如何评估？

- 使用 UV
- 使用 UV 与 DAU 的占比：即日活跃用户中有多少用户使用了该功能
- 生成代码的 UV
- 生成代码满意度

**Comment by fyangstudio** [comment]
暂时不考虑 imgcook 重合功能
