### ISSUE TITLE
RFC: 基于数据模型智能生成代码

### ISSUE THREAD

**Issue by alvinhui** [apptools-lab/AppWorks#464]
## 问题是什么？

一些前端场景，例如表单、表格、列表，其设计和交互比较固定而且是由数据驱动的。这类场景业务量大，技术含量低，规则明确，
可以通过对数据进行分析，直接生成前端代码，由此节约设计师资源，提升前端开发效率。

## 怎么做？

1. 选择数据类型（表单、表格）
    ![image](https://user-images.githubusercontent.com/4392234/91379412-378be280-e855-11ea-94bf-ba2f062504a0.png)
2. 填写数据（JSON or Schema）
    ![image](https://user-images.githubusercontent.com/4392234/91382452-59d52e80-e85c-11ea-8905-ff8f2251cce1.png)
3. 确认字段（可省略）、配置表单项、预览
    ![image](https://user-images.githubusercontent.com/4392234/91384042-40ce7c80-e860-11ea-84b1-d0bbca288f08.png)
4. 生成代码
    ![image](https://user-images.githubusercontent.com/4392234/91381372-d1558e80-e859-11ea-9c6a-e8fad7669c09.png)

### 参考

- 模型驱动：http://suo.im/6nDiPB
- 智能向导：http://suo.im/6gbhSk
- 一体化研发：http://suo.im/5SYmp6

## 如何评估？

- 使用 UV
- 使用 UV 与 DAU 的占比：即日活跃用户中有多少用户使用了该功能
- 生成代码的 UV
- 生成代码满意度

**Comment by Sean1514** [comment]
请问这个功能怎么使用呢
