### ISSUE TITLE
支持添加区块到 vue 文件中

### ISSUE THREAD

**Issue by luhc228** [apptools-lab/AppWorks#584]
### 问题描述
目前不支持添加区块到 vue 文件中

### 方案
支持添加区块代码到 `template` 元素中，并增加相应的依赖引入至 `script` 元素中

**Comment by chengqiang1992** [comment]
问题描述
目前添加区块到 vue 文件中，相关依赖插入位置不正确。目前都是插入在文件第一行，不是vue文件的 <script>中。

方案
应该在 packages/common-service/判断project type是vue还是其他，然后获取 import 或 script位置，再进行插入。另外需要在 vue文件里的 components 里面添加相应的组件名。
