### ISSUE TITLE
RFC: 组件属性可视化配置

### ISSUE THREAD

**Issue by alvinhui** [apptools-lab/AppWorks#602]
通过命名唤起属性配置面板，当光标定位在组件标签代码上时，属性面板出现配置组件属性的表单：

![image](https://user-images.githubusercontent.com/4392234/95583935-7b3a5480-0a6f-11eb-8f2b-28c3c558c394.png)

落地场景：布局组件的配置。

**Comment by imlida** [comment]
这个非常实用，什么时候能用上？

**Comment by imlida** [comment]
把样式面板也加上，非常完美

**Comment by alvinhui** [comment]
@imlida 目前还没有实施的计划

**Comment by qianxuemin** [comment]
现在开发完了吗 在线等 挺急的
