### ISSUE TITLE
RFC: 新增编码辅助功能

### ISSUE THREAD

**Issue by alvinhui** [apptools-lab/AppWorks#603]
新增 iceworks-refactor 插件，包含以下功能：

#### 功能一：删除组件

激活方式：

1. 在侧边栏中删除：「删除组件及其引用」
    ![image](https://user-images.githubusercontent.com/4392234/111116510-12688280-85a1-11eb-9ac7-b93e6a3586a4.png)
2. 在资源管理器中删除：「删除组件及其引用」
    ![image](https://user-images.githubusercontent.com/4392234/111116679-565b8780-85a1-11eb-8f3c-f37831017607.png)
3. 在编辑器中选中代码后右键：「移除组件及其定义和引用」（可通过快捷键执行）
    ![image](https://user-images.githubusercontent.com/4392234/111116983-d124a280-85a1-11eb-82eb-fa9a8240cdf7.png)

### 二、提取代码

圈定部分代码，快速对其进行封装为新的函数、类。

#### 功能一：快速生成前端组件

1. 通过鼠标选中一段 JSX 代码，右键菜单选择「提取为新的组件」：

![image](https://user-images.githubusercontent.com/4392234/95605295-548a1700-0a8b-11eb-836a-8928b3589f93.png)

2. 选中代码处变为引用一个新的组件，并且在文件头将该组件导入：

![image](https://user-images.githubusercontent.com/4392234/95605871-22c58000-0a8c-11eb-9b6e-24097e4b94d9.png)

其他说明：

- 如果代码中有使用到的变量，则设置为新组件的 props，并在使用处进行传递；
- 如果变量只在该代码片段中使用，则会被提取到新的组件文件，并且在原文件中移除声明

#### 参考

- https://marketplace.visualstudio.com/items?itemName=planbcoding.vscode-react-refactor

### 三、变量命名

选择某个变量，帮助快速进行更好的重命名。

#### 功能一：更好的命名推荐

1. 选择一个字符（变量、函数名），右键菜单选择「建议的命名」：
    ![image](https://user-images.githubusercontent.com/4392234/95607762-c9128500-0a8e-11eb-8e2d-f85520edc0c0.png)
2. 弹出选项列表供用户选择，选择某个选项后更改变量命名且更新变量的所有引用处：
    ![image](https://user-images.githubusercontent.com/4392234/95608045-30c8d000-0a8f-11eb-8818-33bd8a04d3e9.png)

#### 功能二：更改命名风格

将字符（变量、函数名）转换命名风格。支持范畴：

- 单个字符
- 文件内的所有字符
- 文件夹内所有文件的所有字符

![](https://cloud.githubusercontent.com/assets/2899448/10712456/3c5e29b6-7a9c-11e5-9ce4-7eb944889696.gif)

常见场景：将常量转换为 upperCase

> 参考：https://github.com/blakeembrey/change-case

## P1: 代码翻译(Code Translation)

把代码从一种编程语言翻译到另一种编程语言：

- classComponent => functionComponent
- CSS => CSS Module
- inlineStyle => CSS Module

#### 输入

```jsx

import React from 'react';
import { ResponsiveGrid } from '@alifd/next';

const { Cell } = ResponsiveGrid;

class Dashboard extends React.Component {
  render() {
    return (
      <ResponsiveGrid gap={20}>
        <Cell colSpan={12}>
          Test
        </Cell>
      </ResponsiveGrid>
    );
  }
}

export default Dashboard;
```

#### 输出

```jsx
import React from 'react';
import { ResponsiveGrid } from '@alifd/next';

const { Cell } = ResponsiveGrid;

const Dashboard = () => {
  return (
    <ResponsiveGrid gap={20}>
      <Cell colSpan={12}>
        Test
      </Cell>
    </ResponsiveGrid>
  );
};

export default Dashboard;
```
#### 参考

VSCode Extension: 

- https://marketplace.visualstudio.com/items?itemName=wix.glean
- https://marketplace.visualstudio.com/items?itemName=angryobject.react-pure-to-class-vscode
- https://marketplace.visualstudio.com/items?itemName=riazxrazor.html-to-jsx

Codemode:

- https://github.com/reactjs/react-codemod#pure-component

AST:

- https://github.com/benjamn/recast
- https://github.com/facebook/jscodeshift
- https://babeljs.io/docs/en/babel-parser

#### 输入

CSS:

```css
.wrap {
  font-size: 14px;
}

.main {
  font-size: 12px;
}
```

jsx:

```jsx
import React from 'react';
import './index.css';

const Dashboard = () => {
  return (
    <div className="wrap">
      <div className="main">
        Test
      </div>
    </div>
  );
};

export default Dashboard;
```

#### 输出

jsx:

```jsx
import React from 'react';
import styles from './index.module.scss';

const Dashboard = () => {
  return (
    <div className={styles.wrap}>
      <div className={styles.main}>
        Test
      </div>
    </div>
  );
};

export default Dashboard;
```

#### 输入

```jsx
import React from 'react';

const Dashboard = () => {
  return (
    <div className={{ fontSize: 14 }}>
      <div className={{ fontSize: 12 }}>
        Test
      </div>
    </div>
  );
};

export default Dashboard;
```

#### 输出

jsx:

```jsx
import React from 'react';
import styles from './index.module.scss';

const Dashboard = () => {
  return (
    <div className={styles.wrap}>
      <div className={styles.main}>
        Test
      </div>
    </div>
  );
};

export default Dashboard;
```

css module:

```scss
.wrap {
  font-size: 14px;

  .main {
    font-size: 12px;
  }
}
```

#### 参考

- https://marketplace.visualstudio.com/items?itemName=gottfired.css2react
- https://marketplace.visualstudio.com/items?itemName=paulmolluzzo.convert-css-in-js
- https://marketplace.visualstudio.com/items?itemName=krizzdewizz.refactorix
- https://marketplace.visualstudio.com/items?itemName=obenjiro.arrr

**Comment by alvinhui** [comment]
## 代码翻译(Code Translation)

把代码从一种编程语言翻译到另一种编程语言。

例如将代码从一种 DSL 翻译到另一种 DSL(Vue to React)。

示例：

```vue
<template>
  <div class="home">
    <HelloWorld msg="Welcome to Your App" />
  </div>
</template>

<script>
import HelloWorld from "@/components/HelloWorld.vue";

export default {
  name: "Home",
  components: {
    HelloWorld
  }
};
</script>
```

转换为：

```jsx
import HelloWorld from "@/components/HelloWorld";

export default function() {
    return (
        <div class="home">
            <HelloWorld msg="Welcome to Your App" />
        </div>
    );
}
```

**Comment by alvinhui** [comment]
## 代码注释生成(Code Summarization)

快速为函数生成有意义的注释。示例：

```diff
+/**
+ * Genereates an action creator for a given model & reducer
+ * 
+ * @param modelName {string} name of model
+ * @param reducerName {string} name of reducer
+ */
createDispatcher(modelName, reducerName) {
    return async (payload, meta) => {
        const action = { type: `${modelName}/${reducerName}` };
        if (typeof payload !== 'undefined') {
            action.payload = payload;
        }
        if (typeof meta !== 'undefined') {
            action.meta = meta;
        }
        return this.dispatch(action);
    };
},
```

**Comment by alvinhui** [comment]
## 代码补全(Code Completion)

给定已经写好的部分代码，能够在指定位置自动预测出后续的代码，包含词汇级别(Token-level)和行级别(Line-level)的补全。

**示例：React 组件编写**

![image](https://user-images.githubusercontent.com/4392234/95644105-ad3acd80-0ae6-11eb-997c-2bdc2bd39442.png)

**Comment by alvinhui** [comment]
## 代码重构(Code Refactoring)

### 提取代码

圈定部分代码，快速对其进行封装为新的函数、类。

**示例：快速生成前端组件。**

1. 通过鼠标选中一段 JSX 代码，右键菜单选择「提取为新的组件」：
    ![image](https://user-images.githubusercontent.com/4392234/95605295-548a1700-0a8b-11eb-836a-8928b3589f93.png)
2. 选中代码处变为引用一个新的组件，并且在文件头将该组件导入：
    ![image](https://user-images.githubusercontent.com/4392234/95605871-22c58000-0a8c-11eb-9b6e-24097e4b94d9.png)

其他说明：

- 如果代码中有使用到的变量，则设置为新组件的 props，并在使用处进行传递；
- 如果变量只在该代码片段中使用，则会被提取到新的组件文件，并且在原文件中移除声明；

### 变量命名

选择某个变量，帮助快速进行更好的重命名。

#### 示例一：更好的命名推荐

1. 选择一个字符（变量、函数名），右键菜单选择「建议的命名」：
    ![image](https://user-images.githubusercontent.com/4392234/95607762-c9128500-0a8e-11eb-8e2d-f85520edc0c0.png)
2. 弹出选项列表供用户选择，选择某个选项后更改变量命名且更新变量的所有引用处：
    ![image](https://user-images.githubusercontent.com/4392234/95608045-30c8d000-0a8f-11eb-8818-33bd8a04d3e9.png)

#### 示例二：更改命名风格

将字符（变量、函数名）转换命名风格。支持范畴：

- 单个字符
- 文件内的所有字符
- 文件夹内所有文件的所有字符

![](https://cloud.githubusercontent.com/assets/2899448/10712456/3c5e29b6-7a9c-11e5-9ce4-7eb944889696.gif)

常见场景：将常量转换为 upperCase

> 参考：https://github.com/blakeembrey/change-case

**Comment by alvinhui** [comment]
## P0: 代码翻译(Code Translation)

把代码从一种编程语言翻译到另一种编程语言：

- classComponent <=> functionComponent
- inlineStyle <=> CSS
- CSS => SCSS

示例：

```vue
<template>
  <div class="home">
    <HelloWorld msg="Welcome to Your App" />
  </div>
</template>

<script>
import HelloWorld from "@/components/HelloWorld.vue";

export default {
  name: "Home",
  components: {
    HelloWorld
  }
};
</script>
```

转换为：

```jsx
import HelloWorld from "@/components/HelloWorld";

export default function() {
    return (
        <div class="home">
            <HelloWorld msg="Welcome to Your App" />
        </div>
    );
}
```

**Comment by alvinhui** [comment]
## P1: 代码重构(Code Refactoring)

### 提取代码

圈定部分代码，快速对其进行封装为新的函数、类。

**示例：快速生成前端组件。**

1. 通过鼠标选中一段 JSX 代码，右键菜单选择「提取为新的组件」：
    ![image](https://user-images.githubusercontent.com/4392234/95605295-548a1700-0a8b-11eb-836a-8928b3589f93.png)
2. 选中代码处变为引用一个新的组件，并且在文件头将该组件导入：
    ![image](https://user-images.githubusercontent.com/4392234/95605871-22c58000-0a8c-11eb-9b6e-24097e4b94d9.png)

其他说明：

- 如果代码中有使用到的变量，则设置为新组件的 props，并在使用处进行传递；
- 如果变量只在该代码片段中使用，则会被提取到新的组件文件，并且在原文件中移除声明；

### 变量命名

选择某个变量，帮助快速进行更好的重命名。

#### 示例一：更好的命名推荐

1. 选择一个字符（变量、函数名），右键菜单选择「建议的命名」：
    ![image](https://user-images.githubusercontent.com/4392234/95607762-c9128500-0a8e-11eb-8e2d-f85520edc0c0.png)
2. 弹出选项列表供用户选择，选择某个选项后更改变量命名且更新变量的所有引用处：
    ![image](https://user-images.githubusercontent.com/4392234/95608045-30c8d000-0a8f-11eb-8818-33bd8a04d3e9.png)

#### 示例二：更改命名风格

将字符（变量、函数名）转换命名风格。支持范畴：

- 单个字符
- 文件内的所有字符
- 文件夹内所有文件的所有字符

![](https://cloud.githubusercontent.com/assets/2899448/10712456/3c5e29b6-7a9c-11e5-9ce4-7eb944889696.gif)

常见场景：将常量转换为 upperCase

> 参考：https://github.com/blakeembrey/change-case

**Comment by alvinhui** [comment]
## P2: 代码补全(Code Completion)

给定已经写好的部分代码，能够在指定位置自动预测出后续的代码，包含词汇级别(Token-level)和行级别(Line-level)的补全。

**示例：React 组件编写**

![image](https://user-images.githubusercontent.com/4392234/95644105-ad3acd80-0ae6-11eb-997c-2bdc2bd39442.png)

**Comment by alvinhui** [comment]
## P3: 代码注释生成(Code Summarization)

快速为函数生成有意义的注释。示例：

```diff
+/**
+ * Genereates an action creator for a given model & reducer
+ * 
+ * @param modelName {string} name of model
+ * @param reducerName {string} name of reducer
+ */
createDispatcher(modelName, reducerName) {
    return async (payload, meta) => {
        const action = { type: `${modelName}/${reducerName}` };
        if (typeof payload !== 'undefined') {
            action.payload = payload;
        }
        if (typeof meta !== 'undefined') {
            action.meta = meta;
        }
        return this.dispatch(action);
    };
},
```

**Comment by luhc228** [comment]
class component to function component:
- https://marketplace.visualstudio.com/items?itemName=wix.glean
- https://marketplace.visualstudio.com/items?itemName=angryobject.react-pure-to-class-vscode

**Comment by alvinhui** [comment]
AST:

- https://github.com/benjamn/recast
- https://babeljs.io/docs/en/babel-parser

**Comment by alvinhui** [comment]
classComponent 2 functionComponent: https://github.com/reactjs/react-codemod#pure-component
