### ISSUE TITLE
根据项目类型过滤物料集合的功能对用户太黑盒

### ISSUE THREAD

**Issue by imsobear** [apptools-lab/AppWorks#656]
### 问题描述/Problem Description

- 目前会针对项目类型过滤物料集合，比如 React 项目只展示 React 的物料集合
- 但是这个能力对用户是黑盒的，用户可能无法理解，甚至有些 case 物料集合 type 写错的时候无法排查

### 建议的方案/Proposal

- 项目类型的判断需要更完整一点，比如将 react external 的情况下项目类型可能判断出错，此时是不是可以降级会原先的 iceworks.type 字段（写在项目 package.json 中）
- 对于项目类型、物料集合类型在哪里透出下，并且告知用户哪几个物料集合不匹配已被过滤（具体在哪里展示没太想好，原先几计划的项目大盘是可以承载的）

**Comment by luhc228** [comment]
项目的物料类型的优先级：
1. 读取项目中 `package.json` 中的 iceworks.type 的配置
2. 读取项目的依赖，是 React/Rax/Vue
3. 默认兜底显示 React 物料

**Comment by imsobear** [comment]
> 项目的物料类型的优先级：
> 
> 1. 读取项目中 `package.json` 中的 iceworks.type 的配置
> 2. 读取项目的依赖，是 React/Rax/Vue
> 3. 默认兜底显示 React 物料

什么意思？
