### ISSUE TITLE
Debug 功能优化

### ISSUE THREAD

**Issue by alvinhui** [apptools-lab/AppWorks#814]
现有功能优化：

1. 启动调试时如果已经打开了 Preview，则不再打开浏览器。当前两个都会打开且会切换跳到浏览器。目前启动调试只有 rax 应用才会打开 Preivew，注意不再打开浏览器的前提是「打开了 Preview」。
    ![image](https://user-images.githubusercontent.com/4392234/111295202-13bfab00-8686-11eb-9678-c929479eb728.png)
2. 当使用手机模式时，图标需要加深显示，有区分度
    ![image](https://user-images.githubusercontent.com/4392234/111295414-4d90b180-8686-11eb-83af-d259056fdd7f.png)
3. Debug 模式下默认开启 [dev-inspector](https://www.npmjs.com/package/build-plugin-dev-inspector)

另外建议将 Preview 功能实现一个单独的插件：iceworks-browser 

1. 允许打开多个 Preview：通过命令面板，以及将启动项添加入 Iceworks Quick Entries
2. 未来的定位和功能参考 [Browser Preview](https://marketplace.visualstudio.com/items?itemName=auchenberg.vscode-browser-preview)，重点是在 WebIDE 下有好的模拟器体验，方便进行代码断点调试。

**Comment by fyangstudio** [comment]
3. Debug 模式下默认开启 dev-inspector

这个目前通过安装 plugin 的方式打开，并且再有 preview 的情况下 `code --goto` 指令 vscode 默认唤起的是 active 的窗口，这个窗口和 preview 有冲突。  目前没啥好的办法避免

**Comment by alvinhui** [comment]
@fyangstudio 当前 preview 就是 active 窗口呀，这个没有冲突吧？

**Comment by fyangstudio** [comment]
AppWorks 插件 目前 建议使用 Chrome devtools
