### ISSUE TITLE
Time master cannot get git url in subproject.

### ISSUE THREAD

**Issue by sspku-yqLiu** [apptools-lab/AppWorks#830]
插件名/Extension: 
Iceworks Time Master

## 您的本地环境信息/Your local environment information

* 操作系统及其版本/System and Version: 
* Node version: 
* npm version: 

## 您遇到的问题及复现步骤/What are your problems and how to reproduce them

When I coding in a subproject, Time Master cannot get git-url correctly. 
For example, when I coding in iceworks/extensions/time-master. Time master will determine it as a local project rather than a subproject of Iceworks.  

## 您期待的正确结果/The right result you're looking forward to

When I coding in subjects (like Iceworks/extensions/time-master), Time Master can deem them as parts of parent projects(Iceworks)

**Comment by fyangstudio** [comment]
暂时不需要 严格的 git url 区分
