### ISSUE TITLE
[question] 设计理念：为什么 Iceworks 生态能力要以 Extension Pack 提供

### ISSUE THREAD

**Issue by screetBloom** [apptools-lab/AppWorks#845]
### 问题描述/Question Description

想了解一下，为什么 ICE 在 VSCode 中的能力要以 Extension Pack 提供
> monorepo 仓库中 iceworks 子 repo  是一个**不携带任何实际能力的** Extension Pack 壳子工程
> 用户使用时安装的也是 iceworks 

<br>

1. 插件机制设计时一般分基础内置插件和外部插件，而**Extension Pack 概念是没有任何内置插件的概念的**
2. 带来的问题是 ice 本身能力全部列举在 extensionPack，但是社区团队使用 ice 体系后，贡献的生态插件就无法作为统一插件子模块融合进去
3. 另外 extensionPack 对各个插件的管控能力也比较弱，如果不是内部插件，存在快捷键冲突等风险

<br>

### 备选的方案1/Alternatives1
Iceworks 插件内部实现一个插件机制

1. **主程序**：Ice 团队负责基础能力的开发和发布
2. **插件接入定义**：对社区提供一份插件接入定义
3. **通用能力**：插件开发时通用 Api（eg. Api.addTreeView）

以便于社区或者业务使用时按需拓展，拓展的能力可以有一个仓库进行集中的收集，比如：**Awesome-Iceworks**

<br>
<br>

### 备选的方案2/Alternatives2
> 单纯的一个思路交流，纯 YY，看起来大概率不太合理

业务或者内部团队如果要定制
1. Fork 仓库，还是 monorepo+ pack 方式去维护，但是升级时可以支持社区或者公司内把基础性质的精选插件一起放到 extensionPack 中
2. 单个仓库分不同文件夹去维护 `iceworks-app`、`iceworks-codemod` 等能力，把 `ExtensionPack` 当成外部精选插件去使用

<br>
<br>

只是看源代码和架构图时对设计理念的好奇，并不是针对这个设计方式进行攻击
> 也比较好奇之前大佬你们是如何思考开源后 iceworks 生态拓展性这个问题的

![image](https://user-images.githubusercontent.com/22092110/119606993-242e9780-be26-11eb-9f64-f1bcf9f1cd58.png)

<br>
<br>

@fyangstudio  @alvinhui 

> 因为 issue 模板中没有 Question 模板，我就按照 Feature 模板进行了提交，「enhancement」labels 可以忽略

<br>

**Comment by fyangstudio** [comment]
感谢您的宝贵建议和提问 😊 。

AppWorks 的初心是降低门槛，提升效率，提高质量，提供美好的开发体验。
目前 VS Code 正则成为最受欢迎的 IDE ，有很大一部分开发者都会用到它。借助 VS Code 我们可以为更多的开发者提供服务。
同时我们也在筹备能一键帮助开发者完成所有环境准备的应用， AppWorks 1.0 版本也会在近期发布。

对于您说的拓展性问题，我们会认真考虑和设计，也希望您能为 AppWorks 提供更多通用能力。
