### ISSUE TITLE
使用区块组装页面-appworks页面点击生成页面没有反应

### ISSUE THREAD

**Issue by Morty7** [apptools-lab/AppWorks#874]
http://localhost:3333/  可以跑起来但是在使用区块组装页面-appworks页面点击生成页面没有反应
![image](https://user-images.githubusercontent.com/42180000/123062412-124d0e00-d43f-11eb-9d9b-47c46ff79d8a.png)

**Comment by luhc228** [comment]
我这边是正常的。可以尝试更新 AppWorks 插件到最新版本。

另外可以帮忙看下控制台的报错信息吗？启动 VS Code 控制台的方式为 Help -> Toggle Develop Tool
