### ISSUE TITLE
AppWorks 插件集 插件优化

### ISSUE THREAD

**Issue by fyangstudio** [apptools-lab/AppWorks#970]
现有插件 18个，其中有些插件较大 ，使用率低 ，不符合整体设计规划，同时还会造成下载耗时较长，先对插件进行梳理。

争议插件：
* [AppWorks - CodeMod](https://marketplace.visualstudio.com/items?itemName=iceworks-team.iceworks-codemod) 规划全部列入 doctor AppLint 体系提供能力支持，现在包含 codemod 较普通，使用引导弱。 **14.4 M**
* [Bookmarks](https://marketplace.visualstudio.com/items?itemName=alefragnani.Bookmarks) 目前使用率较低。**6M**
* [Code Runner](https://marketplace.visualstudio.com/items?itemName=formulahendry.code-runner) 目前使用率较低。**713K**

**Comment by fyangstudio** [comment]
我赞同以上插件全部去除

@imsobear @luhc228 @alvinhui

**Comment by luhc228** [comment]
> 我赞同以上插件全部去除
> 
> @imsobear @luhc228 @alvinhui

+1

**Comment by fyangstudio** [comment]
#971
