### ISSUE TITLE
代码质量扫码报错

### ISSUE THREAD

**Issue by wtl8181** [apptools-lab/AppWorks#973]
![image](https://user-images.githubusercontent.com/45154909/141947402-45b05601-368a-4100-b2ba-38fa9580954f.png)
代码质量扫码报错

**Comment by fyangstudio** [comment]
可以打包 发下 示例项目吗

**Comment by fyangstudio** [comment]
![image](https://user-images.githubusercontent.com/9896768/141949619-b8dde379-65d1-47ad-96a1-81c632aa4cf9.png)
原因是 合并了用户的配置。但插件不具备。

解决方案：  @luhc228  后续 applit 会去除 合并用户配置的行为，期望大家都遵守新的 淘系前端规则
