### ISSUE TITLE
User Defined Saving Path for Logfiles for a one user - many computer scenario.

### ISSUE THREAD

**Issue by ovillani** [apptools-lab/AppWorks#974]
### 问题描述/Problem Description
Often users are using more than one computer. Lets say one at the office, another at home (home-office, very popular these days), on on travel. Anyhow logfiles for this extension are stored locally in the user directory of each computer seperately. So time recordings are not shared amongst different computers. 
With the option to use a user defined path (e.g. on a server or a cloud drive) for the log data one could use this extension on multiple computers. And all recorded times can be summed up.

It is not a defect, only a limitation for all those using more than one computer.

### 建议的方案/Proposal
A solution could be a settings-defined path - or an option to do so - where the logfiles are stored.

### 备选的方案/Alternatives
An alternative could be to store data in a/the project folder itself. Requires a .gitignore entry if git is used.

### 附加信息/Other Information
None at the moment, thanks for this extension anyway!

**Comment by fyangstudio** [comment]
what kind of data do you want to share?
