### ISSUE TITLE
[question] 使用基础组件生产自定义区块组件

### ISSUE THREAD

**Issue by yfcchilly** [apptools-lab/AppWorks#976]
之前用iceworks，发现升级到appworks后，貌似找不到这个功能了，无法使用基础的组件来可视化搭建自定义区块了。如链接中的最后一部分：https://www.w3cschool.cn/iceworks/iceworks-pak13fi7.html

**Comment by luhc228** [comment]
我们在 appworks 中已经不支持可视化搭建自定义区块了，这个功能对页面开发帮助不大，可视化搭建完区块后还需要在源码中改动很多才能用，效率其实还蛮低的
