### ISSUE TITLE
VSCode 中关于使用Doctor检测语法过程中，eslint 检测后的结果和Doctor中的结果不一致

### ISSUE THREAD

**Issue by Yancy1028** [apptools-lab/AppWorks#978]
插件名/Extension: Doctor

## 您的本地环境信息/Your local environment information

* 操作系统及其版本/System and Version: Windows 11 专业版 21H2
* 代码编辑器：VS Code 1.16.2
* Doctor的版本：1.1.7
* Node version: 17.1.0
* npm version: 8.1.2

## 您遇到的问题及复现步骤/What are your problems and how to reproduce them
- 源码已上传至Git：https://gitee.com/some21/app-works-material/tree/master/scaffolds/vue-simple
- 使用`npm run lint` ，无语法错误提示
- vscode 本身格式化以及保存时触发eslint 的fix 同样能够正常执行
- 使用 AppWorks/Doctor 检测时发生eslint `vue/script-indent` 错误
- 以下为图示：
 ### .eslintrc.js
![1640330784120_4686BA85-5C8B-40ba-ACB7-49629B9F22B7](https://user-images.githubusercontent.com/25629163/147331843-5a21aa40-d217-4c17-8fea-e41adb74eb93.png)

![image](https://user-images.githubusercontent.com/25629163/147331896-0f4402cf-e275-47b3-be25-05f48259d143.png)
### IDE的结果
![lQLPDhr9Uf6IbLPNAhTNBBmwPKJ0OTs3ucEBzEhi8cCXAA_1049_532](https://user-images.githubusercontent.com/25629163/147331912-d1e45c54-9762-40a3-99e0-373f37a64550.png)
### Doctor的结果
![image](https://user-images.githubusercontent.com/25629163/147331934-dd1b5235-3905-4b31-a6e4-f7697bf1e796.png)

## 您期待的正确结果/The right result you're looking forward to
- 理论上我的eslint 检测通过后，Appworks/Doctor 的结果也应当保持一致

## 另外针对Doctor 中的功能，希望能够有相关配置可以指定忽略扫描检测的文件

主要针对`typhonjs-escomplex`的代码可维护度的检测，针对与项目本身像`babel.config.js`、`postcss.config.js` 等开发环境配置文件可以考虑无需进行检测，以便于针对实际开发内容进行维护度检测

**Comment by Yancy1028** [comment]
还有一个问题可能不太合理

doctor 里面的 eslint 为啥会检测我的json 文件？如图：

![1640333453984_8B7582E1-A197-404f-BD32-09AD1668640C](https://user-images.githubusercontent.com/25629163/147333128-c922d668-1214-40f6-9d79-5870df8e79e8.png)

目前我暂时把这个json 加入到了.eslintignore 里面了

**Comment by fyangstudio** [comment]
这个是符合预期的，关于提到的几个问题：
### 项目 eslint 运行结果和 Doctor 检测结果不一致
原因：
1. 版本差异，VS Code 插件中和你项目中的规范版本不同。 但总体一致，不是主要原因。
2. ESLint 配置读取方式不同，Doctor 仅合并根目录下的 eslintrc 配置。 ESLint 则是 [文档](https://eslint.bootcss.com/docs/user-guide/configuring) 。这是主要原因，ESLint 读取了你项目中包含的另一份配置，而 Doctor 使用顶层配置。
3. 检测文件未申明 .vue 文件，建议修改脚本为 `eslint --cache --ext .js,.jsx,.ts,.tsx,.vue ./`

结论：
不建议项目中嵌套多份 ESLint 配置，如果你是模板生成类项目，建议子模板项目中的 配置 以 `_` 开头，避免影响主应用配置，包含 ESLint 等其他配置。可参考：https://github.com/ice-lab/react-materials/tree/master/scaffolds/ant-design-lite

### 为什么会检测 package.json
原因：
我们希望 package.json 中不要出现错误的用法，比如 * 的版本 或 使用了有风险的 npm 包。

**Comment by Yancy1028** [comment]
> 2. ESLint 配置读取方式不同，Doctor 仅合并根目录下的 eslintrc 配置。 ESLint 则是 [文档](https://eslint.bootcss.com/docs/user-guide/configuring) 。这是主要原因，ESLint 读取了你项目中包含的另一份配置，而 Doctor 使用顶层配置。

## 实际上我在做Doctor 时，我是通过vscode 单独打开的文件夹 vue-simple 进行检测的，这个情况还需要麻烦你们进一步测试
- 针对将配置文件改为 `_` 的做法我这边会加以尝试，谢谢！
- 针对eslint 的检测我会尝试是应用脚本：`eslint --cache --ext .js,.jsx,.ts,.tsx,.vue ./` 进行尝试，而非 vue 自带的 lint 进行检测？

**Comment by Yancy1028** [comment]
> 什么会检测 package.json

- 针对这个问题，目前因为package.json 没有语法错误，但是会被 Doctor 检测出 存在问题，针对这个文件可能存在误检测？也可能因为我这边的习惯是 `双引号优先` 而导致的检测提示?

**Comment by fyangstudio** [comment]
你的问题 还包含 社区在讨论的  vue lint 和 直接使用 eslint 的问题。

我建议是如果你要用  @icewors/spec (eslint-config-ali)  那么不要使用 vue lint 。因为 eslint-confit-ali  集成了 很多 ts vue 的 parser 和 plugin，这些在 vue lint 中 可能有不符合预期的表现。    正因已经内置了 parser 和 plugin  所以更不建议 你 overrides ts 和 vue 的配置。

**Comment by fyangstudio** [comment]
目前 @icewors/spec vue 链路回归测试正常，这个 issue 暂时关闭，有新的问题 可以重新打开。
