### ISSUE TITLE
代码质量监测 扫描失败

### ISSUE THREAD

**Issue by 13799433448** [apptools-lab/AppWorks#980]
插件名/Extension:  app doctor

## 您的本地环境信息/Your local environment information

* 操作系统及其版本/System and Version: 
* Node version: v14.9.0
* npm version:  6.14.8

## 您遇到的问题及复现步骤/What are your problems and how to reproduce them
使用 质量检测仪进行代码质量监测时， 出现扫描失败的情况

### 报错截图
![image](https://user-images.githubusercontent.com/52238305/149260365-b6b4baec-d9eb-459d-bc80-c0f5d0f3626d.png)
### 代码结构
![image](https://user-images.githubusercontent.com/52238305/149260580-680a2800-df2e-4d4d-b446-3df4732ddc79.png)

![image](https://user-images.githubusercontent.com/52238305/149260517-ce27cf24-49e4-4f25-badf-0b0aa9f48868.png)

**Comment by luhc228** [comment]
<img width="1184" alt="image" src="https://user-images.githubusercontent.com/44047106/154190683-865a6804-9202-4715-a409-56cc3b7443f6.png">
可以打开控制台有什么报错出现吗

**Comment by 13799433448** [comment]
你好，很高兴可以回复我的bug
1. 当我点击 打开质量检测仪时

控制台出现了如下的报错

Message ID: ***@***.***&gt;





2. 当我要进行项目代码质量检查时：



以上，就是全部的报错了，期待您的修复

**Comment by yinxing-ws** [comment]
Same Error

ScreenShot:
![image](https://user-images.githubusercontent.com/20393433/154232343-c53a9889-7763-4b3f-94e0-01564461d804.png)

full short message: "Command failed with exit code 1: /Applications/Visual Studio Code.app/Contents/MacOS/Electron /Users/yinxing/.vscode/extensions/iceworks-team.iceworks-doctor-1.1.7/node_modules/@appworks/doctor/lib/workers/eslint/index.js /Users/yinxing/Project/lp/tmp/12/lp-benefits-brand /Users/yinxing/.vscode/extensions/iceworks-team.iceworks-doctor-1.1.7/node_modules/@appworks/doctor/lib/tmp/ rax-ts undefined"

**Comment by libin-code** [comment]
Same as here:

![image](https://user-images.githubusercontent.com/14896023/162917553-01e45e0f-f688-4b5e-a042-dad40bce5b1b.png)

**Comment by fyangstudio** [comment]
可以 发下 eslintrc 文件的内容吗

**Comment by fyangstudio** [comment]
#1003

**Comment by wangzhengbo** [comment]
文件太多导致失败：originalMessage: 'spawn ENAMETOOLONG',  
由于文件太多，导致命令参数过长

**Comment by wangzhengbo** [comment]
具体失败的是jscodeshift.js命令，jscodeshift.js会将所有扫描的文件拼接起来作为参数传递

**Comment by wangzhengbo** [comment]
@fyangstudio 请问下，文件太多导致的问题，会不会考虑提供修复呢？

**Comment by wangzhengbo** [comment]
> 

Windows 10下的问题
