### ISSUE TITLE
appWorks Doctor进行代码质量检测，如何忽略一些文件&文件夹

### ISSUE THREAD

**Issue by wyong03112636** [apptools-lab/AppWorks#981]
**版本**
- vscode插件 appWorks 1.5.1

**问题**
- 使用vscode插件 appWorks Doctor扫描代码时，eslint可以通过配置eslintignore文件来忽略，后面的重复度&可维护度是如何配置忽略文件呢？

**Comment by fyangstudio** [comment]
重复度 和 复杂度 暂不能配置忽略文件。  
可以考虑 共用 eslint 的 ignore 配置，或者 提供一个 整体忽略的配置。  @luhc228 你觉得呢

**Comment by luhc228** [comment]
> 重复度 和 复杂度 暂不能配置忽略文件。 可以考虑 共用 eslint 的 ignore 配置，或者 提供一个 整体忽略的配置。 @luhc228 你觉得呢

共用 eslint ignore 配置会好点
