### ISSUE TITLE
单独使用@appworks/doctor扫描的eslint信息不全

### ISSUE THREAD

**Issue by dongtianqi** [apptools-lab/AppWorks#982]
这是使用vscode插件给出的结果：
![image](https://user-images.githubusercontent.com/26708377/149890379-86d9d658-fb8d-4bef-aff5-0e8a6cd033b7.png)
这是单独使用@appworks/doctor扫描出来的json
![image](https://user-images.githubusercontent.com/26708377/149890546-70ceac34-c94e-41f0-9e84-656469414af4.png)
我去看了appWorks的源码EslintMessages组件：
![image](https://user-images.githubusercontent.com/26708377/149893036-057a7d71-bffa-4bd1-97f8-0de2635718bb.png)
很困惑为什么单独使用@appworks/doctor会有问题，我也检查了@appworks/doctor的版本，应该不是版本的问题

**Comment by fyangstudio** [comment]
目前 vscode 和 npm 包结果对齐的工作我们正在迭代 ，进展会在这个 issue 下 同步

**Comment by luhc228** [comment]
发布 `@appworks/doctor` 0.4.0 版本，修复了不能扫描 vue 文件的问题，可以重新安装一个 `@appworks/doctor` 这个包试下
