### ISSUE TITLE
@appworks/doctor检测报告结果输出报错

### ISSUE THREAD

**Issue by wyong03112636** [apptools-lab/AppWorks#983]
@appworks/doctor 版本0.3.1
关于检测报告输出有报错
![image](https://user-images.githubusercontent.com/38455783/150056650-07db5c26-e117-4943-b2aa-22b5bdf23b53.png)
![image](https://user-images.githubusercontent.com/38455783/150056841-c61c070e-6f9a-4a8f-84e7-d2213f3e2a81.png)

**Comment by fyangstudio** [comment]
vue 我们正在排期支持

**Comment by wyong03112636** [comment]
好的

**Comment by luhc228** [comment]
@wyong03112636 上面的错误没办法复现出来

**Comment by luhc228** [comment]
@wyong03112636 能提供一个可复现的 demo 吗

**Comment by wyong03112636** [comment]
@luhc228 抱歉之前的报错我也没有复现出来，切换node版本为16.13.2之后是可以扫描成功的。另外想问下，对于weex项目，@appworks/doctor也是支持的吧？

**Comment by wyong03112636** [comment]
发现一个新的问题 包的版本还是0.3.1 
![image](https://user-images.githubusercontent.com/38455783/153543581-06e77523-c0cd-4d15-a47a-7b052a667ab9.png)
扫描两万多行代码，结果各项的分数异常

**Comment by luhc228** [comment]
> 发现一个新的问题 包的版本还是0.3.1 ![image](https://user-images.githubusercontent.com/38455783/153543581-06e77523-c0cd-4d15-a47a-7b052a667ab9.png) 扫描两万多行代码，结果各项的分数异常

发布了 @appworks/doctor  0.4.0 版本，支持了 vue 文件的扫描了，你看下

**Comment by wyong03112636** [comment]
@luhc228 刚升级到0.4.0测试了一下有两个问题：
- 项目里没有添加stylelint相关的配置，扫描报错。输出目录里手动创建`stylelint-result.json`文件就没有报错了
![image](https://user-images.githubusercontent.com/38455783/154202907-8b0cd858-ed47-4485-ad23-6a0dcf2b416e.png)
- 扫描结果不准确，结果不是100就是0，跟上面的截图是一致的
