### ISSUE TITLE
想知道这个项目的迭代方向

### ISSUE THREAD

**Issue by bigsausage** [apptools-lab/AppWorks#986]
想了解这种是迭代是如何评价的呢；

或者说怎么评价当前这个做到什么地步了，还有什么迭代空间呢~

**Comment by luhc228** [comment]
AppWorks 目前还是一直在维护中的，也即将有新功能会上线（比如支持在 VS Code 中开发物料等），可以期待一下。

未来也会在编码辅助方面有进一步的迭代
