### ISSUE TITLE
@appworks/doctor扫描结果不准确

### ISSUE THREAD

**Issue by wyong03112636** [apptools-lab/AppWorks#992]
插件名/@appworks/doctor: 

## 您的本地环境信息/
- @appworks/doctor 0.4.0
* 操作系统及其版本/System and Version: 
* Node version: 13.9.0
* npm version: 6.13.7

## 您遇到的问题及复现步骤
扫描结果不准确，分数太极端。除了100就是0
![image](https://user-images.githubusercontent.com/38455783/159629306-31821452-c014-4c7d-807e-fede562e68bd.png)
![image](https://user-images.githubusercontent.com/38455783/159628168-80e9f238-458a-429a-b98d-a4a9e1e7e043.png)

## 您期待的正确结果
与vscode插件的扫描件结果保持一致
![image](https://user-images.githubusercontent.com/38455783/159628448-fcf0ef05-ed2f-4c7e-8228-3612078ccd63.png)

**Comment by wyong03112636** [comment]
补充：
看了@appworks/doctor 0.4.0包的源码，发现eslint规则最终是使用@applint/eslint-config包提供的规则。发现并没有提供vue框架使用的lint规则。对于vue框架来说最终是使用通用的eslint规则。希望能给出一套适用vue2的lint规则

**Comment by luhc228** [comment]
1. doctor 插件暂时未更新到最新的 @appworks/doctor npm 依赖，近期会支持一下。
2. 100 分应该就是你的文件没有 Lint 问题了，maintainability 为0 是因为目前没有扫描代码可维护度，我们考虑把它去掉吧

**Comment by wyong03112636** [comment]
感谢回复
- 关于lint分数，我是针对@applint/eslint-config下的lint规则写的反例，所以分数不应该为100。
- demo地址：https://github.com/wyong03112636/weex-appworks-test

**Comment by luhc228** [comment]
> 感谢回复
> 
> * 关于lint分数，我是针对@applint/eslint-config下的lint规则写的反例，所以分数不应该为100。
> * demo地址：https://github.com/wyong03112636/weex-appworks-test

项目的依赖版本有点旧。比如一些 babel-preset-* 的依赖（里面依赖很多，搞了很久都不清楚哪个引入了哪个了）。

<img width="1798" alt="image" src="https://user-images.githubusercontent.com/44047106/160572274-5225998f-48b3-4343-ac2d-25fe155ae60f.png">

你可以看下我这个最小的 demo ,是可以 work 的：https://github.com/luhc228/weex-applint-demo

**Comment by wyong03112636** [comment]
> > 感谢回复
> > 
> > * 关于lint分数，我是针对@applint/eslint-config下的lint规则写的反例，所以分数不应该为100。
> > * demo地址：https://github.com/wyong03112636/weex-appworks-test
> 
> 项目的依赖版本有点旧。比如一些 babel-preset-* 的依赖（里面依赖很多，搞了很久都不清楚哪个引入了哪个了）。
> 
> <img alt="image" width="1798" src="https://user-images.githubusercontent.com/44047106/160572274-5225998f-48b3-4343-ac2d-25fe155ae60f.png">
> 
> 你可以看下我这个最小的 demo ,是可以 work 的：https://github.com/luhc228/weex-applint-demo

**Comment by wyong03112636** [comment]
总结一下：
- eslint方面，升级了babel的依赖，可以正常给出分数了。
- maintainability方面，准备去掉这功能。
- repeatability方面，分数还是不太对。我用你的demo复制了几行重复的代码给出结果还是100分
 
![image](https://user-images.githubusercontent.com/38455783/160830792-44530f56-839a-4738-bee7-f3eb0cd47473.png)

**Comment by wyong03112636** [comment]
发现一个问题：
通过disable的方式屏蔽报错或者警告，插件给出的分数会有所改善。通过doctor脚步跑出来的分数不会收到影响。
![image](https://user-images.githubusercontent.com/38455783/161012744-65484315-d14e-4246-9666-944540899594.png)

**Comment by wyong03112636** [comment]
![image](https://user-images.githubusercontent.com/38455783/162657080-247b370a-5b0a-462e-b414-2a8aeb963574.png)
eslint配置里可以加一下weex全局变量吗？

**Comment by fyangstudio** [comment]
doctor 会合并用户 @Iceworks/spec 的 eslintrc 配置，可以在 eslintrc 中配置下

**Comment by wyong03112636** [comment]
![image](https://user-images.githubusercontent.com/38455783/163131948-0a1f7e83-c801-4fc8-b1d3-53814bfc398a.png)
我的eslint配置是这样的，使用vscode doctor插件检测是没问题的，但是用脚本的方式去检测就会有这个问题

**Comment by fyangstudio** [comment]
#1001

**Comment by wyong03112636** [comment]
> 总结一下：
> 
> * eslint方面，升级了babel的依赖，可以正常给出分数了。
> * maintainability方面，准备去掉这功能。
> * repeatability方面，分数还是不太对。我用你的demo复制了几行重复的代码给出结果还是100分
> 
> ![image](https://user-images.githubusercontent.com/38455783/160830792-44530f56-839a-4738-bee7-f3eb0cd47473.png)

@fyangstudio  @luhc228  repeatability结果不准的问题，有时间给解决下
