### ISSUE TITLE
Appworks: import component时怎么插入import { TestComponent } from 'XXX'; 

### ISSUE THREAD

**Issue by 2678041235** [apptools-lab/AppWorks#994]
### 问题描述/Problem Description
我们项目的物料组件components不想每一个小组件就发布一个npm包，最后是以组件库的形式发了一个npm包，里面包含多个组件；
那么生成的物料数据.json文件components字段的数组只会有一项；
我在使用的工程去右键 => Appworks：import component => 点击右侧面板的组件添加时，就会出现:

import  from 'xxx组件库';
render里：< />

那么如何达到我想要的组件库的按需引入方式呢？
import { TestComponent } from 'XXX';

**Comment by luhc228** [comment]
物料数据.json 现在是怎么样的？

**Comment by 2678041235** [comment]
> 物料数据.json 现在是怎么样的？

{
  "type": "react",
  "registry": "内网npm库ip",
  "unpkgHost": "内网unpkg",
  "name": "antd-components",
  "description": "antd业务组件库",
  "components": [
    {
      "languageType": "js",
      "componentType": "antd",
      "homepage": "内网unpkg/@rf/antd-components-v3@0.1.3/build/index.html",
      "description": "@rf/antd-components-v3",
      "categories": [],
      "category": "",
      "screenshot": "内网unpkg/@rf/antd-components-v3@0.1.3/screenshot.png",
      "screenshots": [
        "内网unpkg/@rf/antd-components-v3@0.1.3/screenshot.png"
      ],
      "source": {
        "type": "npm",
        "npm": "@rf/antd-components-v3",
        "version": "0.1.3",
        "registry": "内网npm库ip"
      },
      "dependencies": {},
      "publishTime": "2022-02-16T05:28:06.270Z",
      "updateTime": "2022-03-11T02:34:09.953Z"
    },
    {
      "languageType": "js",
      "componentType": "antd",
      "homepage": "内网unpkg/@rf/antd-components-v4@0.1.3/build/index.html",
      "description": "@rf/antd-components-v4",
      "categories": [],
      "category": "",
      "screenshot": "内网unpkg/@rf/antd-components-v4@0.1.3/screenshot.png",
      "screenshots": [
        "内网unpkg/@rf/antd-components-v4@0.1.3/screenshot.png"
      ],
      "source": {
        "type": "npm",
        "npm": "@rf/antd-components-v4",
        "version": "0.1.3",
        "registry": "内网npm库ip"
      },
      "dependencies": {},
      "publishTime": "2022-02-16T05:28:07.145Z",
      "updateTime": "2022-03-11T02:34:10.906Z"
    }
  ]
}

以上是2个组件库的npm包@rf/antd-components-v3 和@rf/antd-components-v4
每个组件库里都含有多个组件
这份json的生成是模仿appworks/cli 的generate改写了下生成的，因为我们项目的目录结构不是官方自动生成的那种；

期望效果：
如何进一步识别@rf/antd-components-v3下面的组件，需要怎么样改写这份json配置可以达到？
