### ISSUE TITLE
mac上插件一直加载中，无法使用

### ISSUE THREAD

**Issue by jiang263** [apptools-lab/AppWorks#995]
插件名/Extension: 

## 您的本地环境信息/Your local environment information

* 操作系统及其版本/System and Version: 
* Node version: 14.18.1
* npm version: 6.14.15

## 您遇到的问题及复现步骤/What are your problems and how to reproduce them

安装完插件，无法创建项目，一直显示下图加载中
![image](https://user-images.githubusercontent.com/25700952/160781161-117c40d8-fd8d-4bb1-b4b9-bec169be02c1.png)

**Comment by fyangstudio** [comment]
当前的网络正常吗？

**Comment by fyangstudio** [comment]
未复现此问题，暂时关闭 此 issue，如有复现 可 reopen
