### ISSUE TITLE
appworks-doctor 扫描报错

### ISSUE THREAD

**Issue by luhc228** [apptools-lab/AppWorks#997]
项目文件数量太多的话，有可能出现内存溢出
![image](https://user-images.githubusercontent.com/44047106/162920871-c0ce8815-fe47-44fb-bb29-e76861315e2a.png)

**Comment by fyangstudio** [comment]
Doctor 现在可以 迁到 AppLint 上了吗  @luhc228

**Comment by fyangstudio** [comment]
#1001
