### ISSUE TITLE
在windows下AppWorks 新建一个项目启动就报错

### ISSUE THREAD

**Issue by ZYuanCheng** [apptools-lab/AppWorks#998]
插件名/Extension: 

## 您的本地环境信息/Your local environment information

* 操作系统及其版本/System and Version: 
* Node version: v14.18.0
* npm version: 6.14.15

## 您遇到的问题及复现步骤/What are your problems and how to reproduce them
在windows下AppWorks 新建一个项目启动就报错
报错如下：Uncaught SyntaxError: The requested module '/node_modules/react/index.js' does not provide an export named 'Component' (at index.tsx:6:1)

**Comment by luhc228** [comment]
看着跟 AppWorks 插件无关？应该是模板的问题？

你用的哪个模板？

**Comment by ZYuanCheng** [comment]
![image](https://user-images.githubusercontent.com/30103415/163080378-6ee50e06-96a2-47a8-9918-c14a924590ab.png)
我选择的是这个，其他的我没有试，你们自己可以测试一下

**Comment by imsobear** [comment]
没法复现，可以把初始化好的项目提交到 GitHub，我们试一下。

**Comment by ZYuanCheng** [comment]
![image](https://user-images.githubusercontent.com/30103415/163094694-9d97e8f2-f3d7-4a1c-8719-0e7987a16fb7.png)
我昨天启动报错，今天一直加载不出来

**Comment by ZYuanCheng** [comment]
![image](https://user-images.githubusercontent.com/30103415/163095373-9edf816f-8be4-4984-90a4-2c2ce59894d5.png)
![image](https://user-images.githubusercontent.com/30103415/163095393-160d7dd3-3ee7-425f-94cf-334c84ea5f27.png)

**Comment by imsobear** [comment]
@ZYuanCheng 我本地的确没问题，试着重装依赖看看？

![image](https://user-images.githubusercontent.com/2505411/163154967-c4e82dd9-2130-48d4-b73d-a4d33b1a9595.png)

**Comment by ZYuanCheng** [comment]
@imsobear 我是在window10 机器上运行的不行
windows开发环境：
node 14.18.0
npm 6.14.15
我在linux上也不行，也报同样的问题
![image](https://user-images.githubusercontent.com/30103415/163159430-fc70f133-c817-4a8d-b895-91dd4e05a827.png)
linux开发环境：
node 14.18.0
npm 6.14.15

**Comment by imsobear** [comment]
https://github.com/alibaba-fusion/materials/issues/134#issuecomment-981590555 试一下

**Comment by ZYuanCheng** [comment]
@imsobear 这样设置可以，希望修复一下，谢谢！

**Comment by imsobear** [comment]
社区第三方依赖的问题，我们不太好修，我们看下
